{
  pkgs,
  inputs ? null,
  ...
}:

let
  # Install upstream base16-shell into a store path, and bundle your custom
  # base16 theme script into scripts/ as part of the same output.
  #
  # We then link the whole directory into ~/.config/base16-shell via `home.file`
  # as a single mapping (avoids nested-file installation issues).
  base16ShellInstalled = pkgs.stdenvNoCC.mkDerivation {
    pname = "base16-shell-installed";
    version = "0";

    src = pkgs.fetchFromGitHub {
      owner = "chriskempson";
      repo = "base16-shell";
      rev = "master";
      sha256 = "sha256-X89FsG9QICDw3jZvOCB/KsPBVOLUeE7xN3VCtf0DD3E=";
    };

    dontBuild = true;

    installPhase = ''
      runHook preInstall

      mkdir -p "$out"
      cp -R ./* "$out"/

      # Bundle your custom theme into the installed scripts directory.
      mkdir -p "$out/scripts"
      cp "${inputs.dotfiles}/base16-shell/base16-neko.sh" "$out/scripts/base16-neko.sh"

      runHook postInstall
    '';
  };
in

{
  # User-scoped fonts (Home Manager)
  my.home.fonts = {
    # enable = true;
    # Keep the set small (DejaVu + a few nice defaults + emoji).
    # Override here if you want to add/remove fonts later.
    # packages = with pkgs; [ dejavu_fonts liberation_ttf freefont_ttf noto-fonts-color-emoji ];
  };

  imports = [
    ./modules/home/base.nix

    # User-scoped fonts + fontconfig (avoid system-wide font cache work at boot)
    ./modules/home/fonts.nix

    # Home Manager package sets
    #
    # Keep the default (portable) Home Manager profile CLI-only.
    # Desktop/WM-specific modules should be imported by a separate desktop profile.
    ./modules/home/packages/base.nix

    ./modules/home/powershell.nix
  ];

  # Allow Home Manager's Zsh module (completions/plugins), while still using your dotfiles
  # as the entrypoint via the bridge configured in `.nixos/modules/home/base.nix`.

  # ---------------------------------------------------------------------------
  # base16-shell (terminal palette helper)
  #
  # Provide an upstream base16-shell checkout under:
  #   ~/.config/base16-shell
  #
  # The custom theme `base16-neko.sh` is bundled into the derivation output
  # under scripts/ so we only need a single directory link here.
  # ---------------------------------------------------------------------------
  home.file.".config/base16-shell".source = base16ShellInstalled;

  # ---------------------------------------------------------------------------
  # Link CLI dotfiles into $HOME (zsh, tmux, vim, and scripts)
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  # Alacritty
  #
  # Link Alacritty config from the dotfiles flake input into the standard
  # XDG config location used by Alacritty on Linux:
  #   ~/.config/alacritty/alacritty.toml
  # ---------------------------------------------------------------------------
  home.file.".config/alacritty/alacritty.toml".source = inputs.dotfiles + "/.alacritty.toml";
  # Zsh is sourced from the dotfiles repo directly (symlinked), not generated by Home Manager.
  # NOTE: The `inputs.dotfiles` flake input must be configured in `flake.nix` for this to work in pure eval.
  home.file.".zshrc".source = inputs.dotfiles + "/zsh/.zshrc";
  home.file.".p10k.zsh".source = inputs.dotfiles + "/zsh/.p10k.zsh";
  home.file.".dircolors".source = inputs.dotfiles + "/zsh/.dircolors";
  home.file.".osxcolors".source = inputs.dotfiles + "/zsh/.osxcolors";

  # IMPORTANT:
  # Do NOT have Home Manager manage anything under `~/.dotfiles/*`.
  # `~/.dotfiles` is your git working tree; if Home Manager manages it, it will
  # replace tracked files with symlinks into the Nix store (breaking the repo).
  #
  # If you need helper shims (e.g. `nix.zsh`), source them directly from the repo
  # via `~/.zshrc` (which we already symlink from `inputs.dotfiles`).

  home.file.".tmux.conf".source = inputs.dotfiles + "/tmux/.tmux.conf";

  home.file.".vimrc".source = inputs.dotfiles + "/vim/.vimrc";

  # Ensure Vim can find custom colorschemes via :colorscheme
  # by placing them under ~/.vim/colors/
  home.file.".vim/colors".source = inputs.dotfiles + "/vim/colors";

  # vim-plug bootstrap: install `plug.vim` into ~/.vim/autoload so Vim can run `plug#begin()`.
  #
  # This is the standard path vim-plug expects for classic Vim (not Neovim):
  #   ~/.vim/autoload/plug.vim
  home.file.".vim/autoload/plug.vim".source = pkgs.fetchurl {
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim";
    sha256 = "sha256-4JmeVzBIZedfWxXuhjfcTOW6lZF1V/OPfLY9RUtTz7Q=";
  };

  # Install custom scripts to ~/.local/bin (on PATH for most setups)
  home.file.".local/bin" = {
    source = inputs.dotfiles + "/bin";
    recursive = true;
    executable = true;
  };

  # ---------------------------------------------------------------------------
  # Base (cross-platform Home Manager config)
  # ---------------------------------------------------------------------------
  my.home.base = {
    enable = true;

    # Keep these explicit so the profile remains portable and predictable.
    username = "zealsprince";
    homeDirectory = "/home/zealsprince";
    stateVersion = "25.11";

    zsh = {
      enable = true;

      aliases = {
        ll = "ls -l";
        update = "sudo nixos-rebuild switch --flake .";
      };
    };

    git = {
      enable = true;

      # Signing will be configured for OpenPGP (gpg) in the Home Manager base module.
      signingKey = "C6C9724C93A72651A5630079D65684425DD2FF50";

      signCommits = true;

      # Prefer OpenPGP signing (gpg) over 1Password SSH signing.
      use1PasswordSshSigning = false;
    };

    ssh = {
      enable = true;
      enableDefaultConfig = false;
      use1PasswordAgent = true;
      onePasswordAgentSock = "~/.1password/agent.sock";
    };
  };

}
